"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import LayoutWrapper from "@/components/common/LayoutWrapper";
import PageHeader from "@/components/common/PageHeader";
import { getExportJobs } from "@/lib/apiClient";
import { getSessionToken } from "@/lib/authSession";

const reportCards = [
  {
    title: "Assets Report",
    description:
      "View asset category-wise summary, status count and asset availability.",
    href: "/reports/assets",
    tag: "Assets",
    group: "Assets",
  },
  {
    title: "Purchases Report",
    description:
      "Track Work Orders, vendor-wise purchase amount and invoice records.",
    href: "/reports/purchases",
    tag: "Purchases",
    group: "Finance",
  },
  {
    title: "Delivery Report",
    description:
      "View department-wise equipment/material delivery records with receiver tracking.",
    href: "/reports/deliveries",
    tag: "Deliveries",
    group: "Operations",
  },
  {
    title: "Returns Report",
    description:
      "Track returned equipments/materials, return condition, returned by and received details.",
    href: "/reports/returns",
    tag: "Returns",
    group: "Operations",
  },
  {
    title: "Transfers Report",
    description:
      "Track department transfers, IT collection, reassignment and receiver acknowledgement.",
    href: "/reports/transfers",
    tag: "Transfers",
    group: "Operations",
  },
  {
    title: "Warranty Report",
    description:
      "Track warranty expiry, expired assets and upcoming warranty alerts.",
    href: "/reports/warranty",
    tag: "Warranty",
    group: "Assets",
  },
  {
    title: "Maintenance Report",
    description:
      "View asset repair, service status, vendor support and maintenance cost.",
    href: "/reports/maintenance",
    tag: "Maintenance",
    group: "Operations",
  },
  {
    title: "Damaged Assets Report",
    description:
      "Monitor damaged, scrapped, repair-needed and unusable IT assets.",
    href: "/reports/damaged",
    tag: "Damaged",
    group: "Assets",
  },
];

const columnPreview = {
  Summary: ["Report Name", "Group", "Status", "Total Records"],
  Detailed: [
    "Report Name",
    "Group",
    "Department",
    "Status",
    "Owner",
    "Last Updated",
  ],
  Audit: [
    "Report ID",
    "Generated By",
    "Approval Status",
    "Risk Count",
    "Version",
    "Audit Trail",
  ],
};

const exportQueue = [
  {
    name: "Monthly Asset Summary",
    format: "Print/PDF",
    status: "Tracking Active",
  },
  {
    name: "Warranty Review",
    format: "Excel",
    status: "Download Active",
  },
  {
    name: "Maintenance Risk Pack",
    format: "CSV",
    status: "Download Active",
  },
];

const savedReportViews = [
  {
    name: "Monthly Asset Review",
    filter: "Assets | Summary | All departments",
  },
  {
    name: "Warranty Expiry Review",
    filter: "Assets | Audit | Expiring soon",
  },
  {
    name: "Maintenance Follow-up",
    filter: "Operations | Detailed | Pending",
  },
];

const dataSourceStatus = [
  { label: "API Status", value: "Connected" },
  { label: "Last Sync", value: "Live on open" },
  { label: "Records Fetched", value: "Backend report API" },
  { label: "Database", value: "MySQL connected" },
];

const reportReadinessItems = [
  "Live MySQL report APIs connected",
  "CSV export available",
  "Excel-compatible export available",
  "Browser print/PDF available",
];

const reportSystemStatus = [
  "Backend report responses connected",
  "Report branding loaded from database settings",
  "Export tracking jobs connected",
  "Scheduled email requires company SMTP deployment",
];

const panelClassName =
  "rounded-[26px] border border-[#2c3f63] bg-[#18253d] p-5 shadow-sm";
const chipClassName =
  "rounded-full border border-[#314666] bg-[#101a2b] px-3 py-1 text-xs font-semibold text-[#c8d4ec]";
const inputClassName =
  "h-11 rounded-2xl border border-[#314666] bg-[#101a2b] px-4 text-sm text-white outline-none focus:border-[#7c3aed]";

export default function ReportsPage() {
  const [activeGroup, setActiveGroup] = useState("All");
  const [reportView, setReportView] = useState("Summary");
  const [reportTemplate, setReportTemplate] = useState("Executive");
  const [printPreviewMode, setPrintPreviewMode] = useState(false);
  const [recentExports, setRecentExports] = useState([]);
  const [exportHistoryStatus, setExportHistoryStatus] = useState("Loading");

  const loadRecentExports = useCallback(async () => {
    const token = getSessionToken();

    if (!token) {
      setExportHistoryStatus("Login Required");
      return;
    }

    try {
      const exportJobs = await getExportJobs(token, 5);
      setRecentExports(exportJobs || []);
      setExportHistoryStatus("Connected");
    } catch {
      setExportHistoryStatus("Unavailable");
    }
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => {
      loadRecentExports();
    }, 0);

    return () => clearTimeout(timer);
  }, [loadRecentExports]);

  const filteredReports = useMemo(() => {
    return reportCards.filter((report) => {
      const matchesGroup = activeGroup === "All" || report.group === activeGroup;

      return matchesGroup;
    });
  }, [activeGroup]);

  return (
    <LayoutWrapper>
      {!printPreviewMode && (
        <PageHeader
          title="Reports"
          description="Open backend-connected reports, switch report view and track export readiness."
        />
      )}

      <section className={panelClassName}>
        <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8fa4c7]">
              Report Builder
            </p>
            <h2 className="mt-1 text-lg font-bold text-white">
              Prepare filters and choose export format
            </h2>
            <p className="mt-1 max-w-3xl text-sm text-[#8fa4c7]">
              These controls drive backend-connected report pages. Export
              tracking is active; scheduled delivery will use the same choices
              after SMTP configuration.
            </p>
          </div>

          <div className="grid w-full grid-cols-1 gap-3 sm:grid-cols-2 xl:max-w-lg">
            <select
              value={activeGroup}
              onChange={(event) => setActiveGroup(event.target.value)}
              className={inputClassName}
            >
              <option value="All">All Groups</option>
              <option value="Assets">Assets</option>
              <option value="Operations">Operations</option>
              <option value="Finance">Finance</option>
            </select>
            <select
              className={inputClassName}
              value={reportView}
              onChange={(event) => setReportView(event.target.value)}
            >
              <option value="Summary">Summary View</option>
              <option value="Detailed">Detailed View</option>
              <option value="Audit">Audit View</option>
            </select>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-2">
          <div className="rounded-[24px] border border-[#314666] bg-[#101a2b] p-4">
            <p className="text-sm font-bold text-white">Column Visibility</p>
            <div className="mt-3 flex flex-wrap gap-2">
              {columnPreview[reportView].map((column) => (
                <span key={column} className={chipClassName}>
                  {column}
                </span>
              ))}
            </div>
          </div>

          <div className="rounded-[24px] border border-[#314666] bg-[#101a2b] p-4">
            <p className="text-sm font-bold text-white">Export Queue</p>
            <div className="mt-3 space-y-2">
              {exportQueue.map((item) => (
                <div
                  key={`${item.name}-${item.format}`}
                  className="flex items-center justify-between gap-3 rounded-2xl border border-[#314666] bg-[#18253d] px-3 py-2 text-sm"
                >
                  <span className="font-semibold text-white">{item.name}</span>
                  <span className={chipClassName}>
                    {item.format} | {item.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-4 flex flex-col gap-3 sm:flex-row">
          <select
            value={reportTemplate}
            onChange={(event) => setReportTemplate(event.target.value)}
            className={`${inputClassName} sm:w-64`}
          >
            <option value="Executive">Executive Template</option>
            <option value="Standard">Standard Template</option>
            <option value="Audit">Audit Template</option>
            <option value="Compliance">Compliance Template</option>
          </select>
          <button
            type="button"
            onClick={() => setPrintPreviewMode((current) => !current)}
            className="inline-flex h-11 items-center justify-center rounded-2xl border border-[#314666] bg-[#101a2b] px-4 text-sm font-semibold text-white hover:bg-[#122038]"
          >
            {printPreviewMode ? "Exit Preview" : "Print Preview"}
          </button>
          <div className="flex flex-wrap gap-2">
            {[
              ["Print/PDF Export", "Active with browser print"],
              ["Excel Export", "Active as spreadsheet download"],
              ["Scheduled Email", "Requires SMTP setup"],
            ].map(([item, status]) => (
              <div
                key={item}
                className="rounded-2xl border border-[#314666] bg-[#101a2b] px-4 py-3"
              >
                <p className="text-sm font-semibold text-white">{item}</p>
                <p className="mt-1 text-xs text-[#8fa4c7]">{status}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className={panelClassName}>
          <div className="mb-4 flex items-center justify-between gap-3">
            <h2 className="text-lg font-bold text-white">Recent Exports</h2>
            <span className={chipClassName}>{exportHistoryStatus}</span>
          </div>
          <div className="space-y-3">
            {recentExports.length === 0 && (
              <p className="rounded-2xl border border-[#314666] bg-[#101a2b] px-4 py-3 text-sm text-[#8fa4c7]">
                No backend export tracking jobs are available yet.
              </p>
            )}
            {recentExports.map((item) => (
              <div
                key={item.exportJobId}
                className="flex flex-col gap-2 rounded-2xl border border-[#314666] bg-[#101a2b] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
              >
                <div>
                  <p className="text-sm font-semibold text-white">
                    {item.exportModule}
                  </p>
                  <p className="mt-1 text-xs text-[#8fa4c7]">
                    {item.exportType} | {item.rowCount ?? 0} rows
                  </p>
                </div>
                <span className={chipClassName}>{item.exportStatus}</span>
              </div>
            ))}
          </div>
        </div>

        <div className={panelClassName}>
          <h2 className="text-lg font-bold text-white">Saved Report Views</h2>
          <div className="mt-4 space-y-3">
            {savedReportViews.map((view) => (
              <div
                key={view.name}
                className="rounded-2xl border border-[#314666] bg-[#101a2b] p-3"
              >
                <p className="text-sm font-bold text-white">{view.name}</p>
                <p className="mt-1 text-xs font-semibold text-[#8fa4c7]">
                  {view.filter}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className={panelClassName}>
          <h2 className="text-lg font-bold text-white">Data Source Status</h2>
          <div className="mt-4 space-y-3">
            {dataSourceStatus.map((item) => (
              <div
                key={item.label}
                className="flex justify-between gap-3 rounded-2xl border border-[#314666] bg-[#101a2b] px-3 py-2 text-sm"
              >
                <span className="font-semibold text-[#8fa4c7]">{item.label}</span>
                <span className="text-right font-bold text-white">
                  {item.value}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className={panelClassName}>
          <h2 className="text-lg font-bold text-white">Report Readiness</h2>
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {reportReadinessItems.map((item) => (
              <div
                key={item}
                className="rounded-2xl border border-[#314666] bg-[#101a2b] p-3 text-sm font-semibold text-[#c8d4ec]"
              >
                {item}
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-[26px] border border-amber-500/30 bg-amber-500/10 p-5 shadow-sm">
          <h2 className="text-lg font-bold text-amber-100">Report System Status</h2>
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {reportSystemStatus.map((item) => (
              <div
                key={item}
                className="rounded-2xl border border-amber-500/20 bg-[#101a2b]/60 p-3 text-sm font-semibold text-amber-100"
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">
        {filteredReports.map((report) => (
          <Link
            key={report.href}
            href={report.href}
            className="group rounded-[26px] border border-[#2c3f63] bg-[#18253d] p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#445c84]"
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <span className={chipClassName}>{report.tag}</span>
                <h2 className="mt-4 text-lg font-bold text-white">{report.title}</h2>
                <p className="mt-2 text-sm leading-6 text-[#8fa4c7]">
                  {report.description}
                </p>
              </div>

              <span className="rounded-full border border-[#314666] bg-[#101a2b] px-3 py-2 text-sm font-bold text-white">
                Open
              </span>
            </div>

            <div className="mt-5 border-t border-[#2c3f63] pt-4">
              <p className="text-sm font-semibold text-[#c8d4ec]">
                Open Report
              </p>
            </div>
          </Link>
        ))}
      </section>
    </LayoutWrapper>
  );
}
