"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import LayoutWrapper from "@/components/common/LayoutWrapper";
import PageHeader from "@/components/common/PageHeader";

const reportCards = [
  {
    title: "Assets Report",
    description:
      "View asset category-wise summary, status count and asset availability.",
    href: "/reports/assets",
    tag: "Assets",
    group: "Assets",
  },
  {
    title: "Purchases Report",
    description:
      "Track purchase orders, vendor-wise purchase amount and invoice records.",
    href: "/reports/purchases",
    tag: "Purchases",
    group: "Finance",
  },
  {
    title: "Delivery Report",
    description:
      "View employee-wise and department-wise equipment/material delivery records.",
    href: "/reports/deliveries",
    tag: "Deliveries",
    group: "Operations",
  },
  {
    title: "Returns Report",
    description:
      "Track returned equipments/materials, return condition, returned by and received details.",
    href: "/reports/returns",
    tag: "Returns",
    group: "Operations",
  },
  {
    title: "Warranty Report",
    description:
      "Track warranty expiry, expired assets and upcoming warranty alerts.",
    href: "/reports/warranty",
    tag: "Warranty",
    group: "Assets",
  },
  {
    title: "Maintenance Report",
    description:
      "View asset repair, service status, vendor support and maintenance cost.",
    href: "/reports/maintenance",
    tag: "Maintenance",
    group: "Operations",
  },
  {
    title: "Damaged Assets Report",
    description:
      "Monitor damaged, scrapped, repair-needed and unusable IT assets.",
    href: "/reports/damaged",
    tag: "Damaged",
    group: "Assets",
  },
];

const recentExports = [
  {
    name: "Asset Summary CSV",
    module: "Assets",
    date: "2026-06-20",
    status: "Downloaded",
  },
  {
    name: "Warranty Review",
    module: "Warranty",
    date: "2026-06-18",
    status: "Preview",
  },
  {
    name: "Maintenance Cost",
    module: "Maintenance",
    date: "2026-06-15",
    status: "Pending Backend",
  },
];

export default function ReportsPage() {
  const [search, setSearch] = useState("");
  const [activeGroup, setActiveGroup] = useState("All");
  const [reportView, setReportView] = useState("Summary");
  const [reportTemplate, setReportTemplate] = useState("Executive");
  const [printPreviewMode, setPrintPreviewMode] = useState(false);

  const filteredReports = useMemo(() => {
    return reportCards.filter((report) => {
      const matchesSearch = `${report.title} ${report.description} ${report.tag}`
        .toLowerCase()
        .includes(search.toLowerCase());
      const matchesGroup = activeGroup === "All" || report.group === activeGroup;

      return matchesSearch && matchesGroup;
    });
  }, [search, activeGroup]);
  const columnPreview = {
    Summary: ["Report Name", "Group", "Status", "Total Records"],
    Detailed: [
      "Report Name",
      "Group",
      "Department",
      "Status",
      "Owner",
      "Last Updated",
    ],
    Audit: [
      "Report ID",
      "Generated By",
      "Approval Status",
      "Risk Count",
      "Version",
      "Audit Trail",
    ],
  };
  const exportQueue = [
    {
      name: "Monthly Asset Summary",
      format: "PDF",
      status: "Requested",
    },
    {
      name: "Warranty Review",
      format: "Excel",
      status: "Processing",
    },
    {
      name: "Maintenance Risk Pack",
      format: "PDF",
      status: "Ready after backend",
    },
  ];
  const savedReportViews = [
    {
      name: "Monthly Asset Review",
      filter: "Assets | Summary | All departments",
    },
    {
      name: "Warranty Expiry Review",
      filter: "Assets | Audit | Expiring soon",
    },
    {
      name: "Maintenance Follow-up",
      filter: "Operations | Detailed | Pending",
    },
  ];
  const scheduledReports = [
    {
      name: "Weekly IT Asset Summary",
      frequency: "Weekly",
      format: "PDF",
      recipients: "IT Admins",
      status: "Active after backend",
    },
    {
      name: "Monthly Warranty Review",
      frequency: "Monthly",
      format: "Excel",
      recipients: "Super Admins",
      status: "Draft",
    },
  ];
  const dataSourceStatus = [
    { label: "API Status", value: "Pending Backend" },
    { label: "Last Sync", value: "Frontend demo" },
    { label: "Records Fetched", value: "Sample data" },
    { label: "Database", value: "MySQL planned" },
  ];
  const frontendQaItems = [
    "Mobile and laptop spacing review",
    "Print footer and watermark review",
    "Table overflow and compact mode review",
    "Dark mode contrast review",
  ];
  const cleanupChecklist = [
    "Remove frontend demo labels",
    "Connect PDF and Excel export APIs",
    "Bind report branding to database settings",
    "Replace sample data with backend responses",
  ];

  return (
    <LayoutWrapper>
      <div
        className={
          printPreviewMode
            ? "rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"
            : ""
        }
      >
      {!printPreviewMode && (
        <PageHeader
          title="Reports"
          description="View IT asset reports, purchase summaries, deliveries, returns, warranty, maintenance and damaged asset records."
        />
      )}

      <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Report Workspace
            </p>
            <h2 className="mt-1 text-lg font-bold text-gray-900">
              Template and print preview controls
            </h2>
          </div>
          <div className="flex flex-col gap-2 sm:flex-row">
            <select
              value={reportTemplate}
              onChange={(event) => setReportTemplate(event.target.value)}
              className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm outline-none focus:border-gray-900"
            >
              <option value="Executive">Executive Template</option>
              <option value="Standard">Standard Template</option>
              <option value="Audit">Audit Template</option>
              <option value="Compliance">Compliance Template</option>
            </select>
            <button
              type="button"
              onClick={() => setPrintPreviewMode((current) => !current)}
              className="rounded-xl border border-gray-900 bg-gray-900 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-800"
            >
              {printPreviewMode ? "Exit Preview" : "Print Preview"}
            </button>
          </div>
        </div>
        <p className="mt-3 text-sm text-gray-600">
          Selected template: {reportTemplate}. Backend phase will connect this
          template choice to actual PDF/Excel generation.
        </p>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-gray-500">Total Reports</p>
          <h2 className="mt-2 text-3xl font-bold text-gray-900">7</h2>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-gray-500">Asset Reports</p>
          <h2 className="mt-2 text-3xl font-bold text-gray-900">2</h2>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-gray-500">Operational Reports</p>
          <h2 className="mt-2 text-3xl font-bold text-gray-900">4</h2>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-gray-500">Finance Reports</p>
          <h2 className="mt-2 text-3xl font-bold text-gray-900">1</h2>
        </div>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm lg:col-span-2">
          <h2 className="text-lg font-bold text-gray-900">Recent Exports</h2>
          <div className="mt-4 divide-y divide-gray-100">
            {recentExports.map((item) => (
              <div
                key={`${item.name}-${item.date}`}
                className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"
              >
                <div>
                  <p className="text-sm font-semibold text-gray-900">
                    {item.name}
                  </p>
                  <p className="mt-1 text-xs text-gray-500">
                    {item.module} | {item.date}
                  </p>
                </div>
                <span className="w-fit rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-semibold text-gray-700">
                  {item.status}
                </span>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-5 shadow-sm">
          <h2 className="text-lg font-bold text-yellow-900">
            Backend Export Queue
          </h2>
          <p className="mt-2 text-sm leading-6 text-yellow-800">
            PDF export, Excel export, scheduled reports and email summary will
            be connected after backend APIs and database are ready.
          </p>
        </div>
      </section>

      <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Report Builder Preview
            </p>
            <h2 className="mt-1 text-lg font-bold text-gray-900">
              Prepare filters before backend export jobs
            </h2>
            <p className="mt-1 max-w-3xl text-sm text-gray-600">
              These controls are frontend-ready. Backend integration will use
              the same choices for PDF, Excel and scheduled report generation.
            </p>
          </div>

          <div className="grid w-full grid-cols-1 gap-3 sm:grid-cols-2 xl:max-w-2xl xl:grid-cols-3">
            <input
              type="text"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search reports..."
              className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm outline-none focus:border-gray-900"
            />
            <select
              value={activeGroup}
              onChange={(event) => setActiveGroup(event.target.value)}
              className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm outline-none focus:border-gray-900"
            >
              <option value="All">All Groups</option>
              <option value="Assets">Assets</option>
              <option value="Operations">Operations</option>
              <option value="Finance">Finance</option>
            </select>
            <select
              className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm outline-none focus:border-gray-900"
              value={reportView}
              onChange={(event) => setReportView(event.target.value)}
            >
              <option value="Summary">Summary View</option>
              <option value="Detailed">Detailed View</option>
              <option value="Audit">Audit View</option>
            </select>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[1fr_1fr]">
          <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
            <p className="text-sm font-bold text-gray-900">
              Column Visibility Preview
            </p>
            <div className="mt-3 flex flex-wrap gap-2">
              {columnPreview[reportView].map((column) => (
                <span
                  key={column}
                  className="rounded-full border border-gray-200 bg-white px-3 py-1 text-xs font-semibold text-gray-700"
                >
                  {column}
                </span>
              ))}
            </div>
          </div>

          <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
            <p className="text-sm font-bold text-gray-900">
              Export Queue Preview
            </p>
            <div className="mt-3 space-y-2">
              {exportQueue.map((item) => (
                <div
                  key={`${item.name}-${item.format}`}
                  className="flex items-center justify-between gap-3 rounded-xl bg-white px-3 py-2 text-sm"
                >
                  <span className="font-semibold text-gray-900">
                    {item.name}
                  </span>
                  <span className="rounded-full border border-gray-200 bg-gray-50 px-2 py-1 text-xs font-semibold text-gray-600">
                    {item.format} | {item.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">
          {["PDF Export", "Excel Export", "Scheduled Email"].map((item) => (
            <div
              key={item}
              className="rounded-xl border border-gray-100 bg-gray-50 px-4 py-3"
            >
              <p className="text-sm font-semibold text-gray-900">{item}</p>
              <p className="mt-1 text-xs text-gray-500">
                Backend connection pending
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900">
            Saved Report Views
          </h2>
          <div className="mt-4 space-y-3">
            {savedReportViews.map((view) => (
              <div
                key={view.name}
                className="rounded-xl border border-gray-100 bg-gray-50 p-3"
              >
                <p className="text-sm font-bold text-gray-900">{view.name}</p>
                <p className="mt-1 text-xs font-semibold text-gray-500">
                  {view.filter}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900">
            Scheduled Reports
          </h2>
          <div className="mt-4 space-y-3">
            {scheduledReports.map((report) => (
              <div
                key={report.name}
                className="rounded-xl border border-gray-100 bg-gray-50 p-3"
              >
                <div className="flex items-start justify-between gap-3">
                  <p className="text-sm font-bold text-gray-900">
                    {report.name}
                  </p>
                  <span className="rounded-full border border-gray-200 bg-white px-2 py-1 text-xs font-semibold text-gray-600">
                    {report.status}
                  </span>
                </div>
                <p className="mt-2 text-xs font-semibold text-gray-500">
                  {report.frequency} | {report.format} | {report.recipients}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900">
            Data Source Status
          </h2>
          <div className="mt-4 space-y-3">
            {dataSourceStatus.map((item) => (
              <div
                key={item.label}
                className="flex justify-between gap-3 rounded-xl bg-gray-50 px-3 py-2 text-sm"
              >
                <span className="font-semibold text-gray-500">
                  {item.label}
                </span>
                <span className="text-right font-bold text-gray-900">
                  {item.value}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900">
            Frontend QA Checklist
          </h2>
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {frontendQaItems.map((item) => (
              <div
                key={item}
                className="rounded-xl border border-gray-100 bg-gray-50 p-3 text-sm font-semibold text-gray-700"
              >
                {item}
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-5 shadow-sm">
          <h2 className="text-lg font-bold text-yellow-900">
            Final Frontend Cleanup Checklist
          </h2>
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {cleanupChecklist.map((item) => (
              <div
                key={item}
                className="rounded-xl border border-yellow-200 bg-white/70 p-3 text-sm font-semibold text-yellow-900"
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">
        {filteredReports.map((report) => (
          <Link
            key={report.href}
            href={report.href}
            className="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-gray-300 hover:shadow-md"
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <span className="inline-flex rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-semibold text-gray-600">
                  {report.tag}
                </span>

                <h2 className="mt-4 text-lg font-bold text-gray-900 group-hover:text-black">
                  {report.title}
                </h2>

                <p className="mt-2 text-sm leading-6 text-gray-600">
                  {report.description}
                </p>
              </div>

              <span className="rounded-full bg-gray-100 px-3 py-2 text-sm font-bold text-gray-700 group-hover:bg-gray-900 group-hover:text-white">
                Open
              </span>
            </div>

            <div className="mt-5 border-t border-gray-100 pt-4">
              <p className="text-sm font-semibold text-gray-700">
                Open Report
              </p>
            </div>
          </Link>
        ))}
      </section>

      <section className="mt-6 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
        <h3 className="text-lg font-bold text-gray-900">Report Note</h3>

        <p className="mt-2 text-sm leading-6 text-gray-600">
          These reports are currently using sample frontend data. After MySQL
          backend integration, all reports will show real-time asset,
          purchase, delivery, return, warranty and maintenance records.
        </p>
      </section>
      </div>
    </LayoutWrapper>
  );
}
