"use client";

import { useEffect, useState } from "react";
import BackButton from "./BackButton";
import LayoutWrapper from "./LayoutWrapper";
import PageHeader from "./PageHeader";
import ReportExportButtons from "./ReportExportButtons";

const REPORT_BRANDING_KEY = "itReportBranding";
const defaultBranding = {
  companyName: "Siddharth IT Department",
  companyEmail: "admin@company.com",
  companyPhone: "+91 98765 43210",
  companyAddress: "Main Office, Maharashtra, India",
  reportLogoText: "IT",
  reportPreparedBy: "IT Department",
  reportClassification: "Internal",
};

export default function ReportPageShell({
  title,
  description,
  data = [],
  fileName,
  children,
}) {
  const [branding, setBranding] = useState(defaultBranding);
  const [compactTable, setCompactTable] = useState(false);
  const reportId = `${fileName.toUpperCase()}-2026`;
  const reportVersion = "v1.0";
  const generatedDate = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  const generatedTime = new Date().toLocaleTimeString("en-IN", {
    hour: "2-digit",
    minute: "2-digit",
  });
  const attentionWords = [
    "Pending",
    "Damaged",
    "Expired",
    "Maintenance",
    "Rejected",
    "Under Review",
    "Under Inspection",
    "Cancelled",
    "Needs Repair",
  ];
  const attentionRecords = data.filter((item) =>
    Object.values(item).some((value) =>
      attentionWords.some((word) => String(value).includes(word))
    )
  ).length;
  const completedRecords = data.filter((item) =>
    ["Completed", "Delivered", "Returned", "Received", "Active", "Approved"].some(
      (word) => Object.values(item).some((value) => String(value).includes(word))
    )
  ).length;
  const appliedFilters = [
    { label: "Date Range", value: "All available records" },
    { label: "Department", value: "All departments" },
    { label: "Status", value: "All statuses" },
    { label: "View", value: "Audit-ready summary" },
  ];
  const executiveSummary = [
    { label: "Total Records", value: data.length },
    { label: "Completed / Active", value: completedRecords },
    { label: "Needs Attention", value: attentionRecords },
    { label: "Report Version", value: reportVersion },
  ];
  const tableOfContents = [
    "Cover Page",
    "Executive Summary",
    "Applied Filters",
    "Attention Highlights",
    "Chart Preview",
    "Detailed Records",
    "Reviewer Notes",
    "Approval & Sign-off",
  ];
  const chartPreview = [
    { label: "Completed", value: completedRecords },
    { label: "Attention", value: attentionRecords },
    {
      label: "Remaining",
      value: Math.max(data.length - completedRecords - attentionRecords, 0),
    },
  ];
  const maxChartValue = Math.max(...chartPreview.map((item) => item.value), 1);
  const auditTrail = [
    { label: "Generated By", value: branding.reportPreparedBy },
    { label: "Last Modified By", value: "Frontend Review User" },
    { label: "Approval Status", value: "Pending backend approval" },
    { label: "Audit Mode", value: "Preview only" },
  ];
  const mobileRecords = data.slice(0, 4).map((item) =>
    Object.entries(item)
      .filter(([, value]) => value !== "" && value !== null && value !== undefined)
      .slice(0, 5)
  );

  useEffect(() => {
    const savedBranding = JSON.parse(
      localStorage.getItem(REPORT_BRANDING_KEY) || "null"
    );

    if (savedBranding) {
      setTimeout(() => {
        setBranding((current) => ({ ...current, ...savedBranding }));
      }, 0);
    }
  }, []);

  return (
    <LayoutWrapper>
      <PageHeader title={title} description={description} />

      <section
        className={`print-area relative overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm ${
          compactTable ? "report-compact" : ""
        }`}
      >
        <div className="report-watermark pointer-events-none absolute inset-0 flex items-center justify-center text-6xl font-bold uppercase text-gray-100">
          {branding.reportClassification}
        </div>
        <div className="relative z-10 border-b border-gray-200 bg-white px-5 py-4">
          <div className="grid gap-4 lg:grid-cols-[1.3fr_0.7fr] lg:items-start">
            <div className="flex items-start gap-4">
              <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-gray-200 bg-gray-900 text-lg font-bold text-white">
                {branding.reportLogoText}
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  IT Assets & Equipment Management
                </p>
                <h2 className="mt-1 text-xl font-bold text-gray-900">
                  {branding.companyName}
                </h2>
                <p className="mt-1 text-sm leading-6 text-gray-600">
                  {branding.companyAddress} | {branding.companyEmail} |{" "}
                  {branding.companyPhone}
                </p>
              </div>
            </div>

            <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Report ID
                  </p>
                  <p className="mt-1 font-bold text-gray-900">{reportId}</p>
                </div>
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Generated
                  </p>
                  <p className="mt-1 font-bold text-gray-900">
                    {generatedDate}, {generatedTime}
                  </p>
                </div>
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Prepared By
                  </p>
                  <p className="mt-1 font-bold text-gray-900">
                    {branding.reportPreparedBy}
                  </p>
                </div>
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Status
                  </p>
                  <p className="mt-1 font-bold text-gray-900">
                    Frontend Preview
                  </p>
                </div>
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Version
                  </p>
                  <p className="mt-1 font-bold text-gray-900">
                    {reportVersion}
                  </p>
                </div>
                <div>
                  <p className="font-semibold uppercase tracking-wide text-gray-500">
                    Last Refreshed
                  </p>
                  <p className="mt-1 font-bold text-gray-900">
                    {generatedTime}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-5 border-t border-gray-200 pt-4">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  Official Report
                </p>
                <h1 className="mt-1 text-2xl font-bold text-gray-900">
                  {title}
                </h1>
                <p className="mt-1 max-w-4xl text-sm leading-6 text-gray-600">
                  {description}
                </p>
              </div>

              <div className="no-print flex flex-col gap-3 sm:flex-row sm:items-center">
                <BackButton href="/reports" label="Reports" />
                <button
                  type="button"
                  aria-label="Toggle compact report table density"
                  onClick={() => setCompactTable((current) => !current)}
                  className="inline-flex justify-center rounded-xl border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-100"
                >
                  {compactTable ? "Normal Table" : "Compact Table"}
                </button>
                <ReportExportButtons data={data} fileName={fileName} />
              </div>
            </div>

            <div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-gray-600">
              <span className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1">
                Classification: {branding.reportClassification}
              </span>
              <span className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1">
                Source: Frontend Demo Data
              </span>
              <span className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1">
                Backend: Pending
              </span>
              <span className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1">
                Records: {data.length}
              </span>
            </div>
          </div>
        </div>

        <div className="relative z-10 space-y-6 p-5">
          <section className="report-cover report-section rounded-2xl border border-gray-200 bg-gray-50 p-6">
            <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr] lg:items-end">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  Report Cover Page
                </p>
                <h2 className="mt-3 text-3xl font-bold text-gray-900">
                  {title}
                </h2>
                <p className="mt-3 max-w-3xl text-sm leading-6 text-gray-600">
                  {description}
                </p>
              </div>
              <div className="rounded-2xl border border-gray-200 bg-white p-4 text-sm">
                <div className="flex justify-between gap-4 py-2">
                  <span className="font-semibold text-gray-500">Period</span>
                  <span className="font-bold text-gray-900">
                    All available records
                  </span>
                </div>
                <div className="flex justify-between gap-4 border-t border-gray-100 py-2">
                  <span className="font-semibold text-gray-500">
                    Prepared By
                  </span>
                  <span className="font-bold text-gray-900">
                    {branding.reportPreparedBy}
                  </span>
                </div>
                <div className="flex justify-between gap-4 border-t border-gray-100 py-2">
                  <span className="font-semibold text-gray-500">
                    Confidentiality
                  </span>
                  <span className="font-bold text-gray-900">
                    {branding.reportClassification}
                  </span>
                </div>
              </div>
            </div>
          </section>

          <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Table Of Contents
            </p>
            <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-4">
              {tableOfContents.map((item, index) => (
                <div
                  key={item}
                  className="flex items-center gap-3 rounded-xl bg-gray-50 px-3 py-2 text-sm font-semibold text-gray-700"
                >
                  <span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-xs font-bold text-gray-900">
                    {index + 1}
                  </span>
                  {item}
                </div>
              ))}
            </div>
          </section>

          <section className="report-section grid grid-cols-1 gap-4 xl:grid-cols-[1.25fr_0.75fr]">
            <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
              <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                Executive Summary
              </p>
              <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">
                {executiveSummary.map((item) => (
                  <div
                    key={item.label}
                    className="rounded-xl border border-gray-100 bg-gray-50 p-3"
                  >
                    <p className="text-xs font-semibold text-gray-500">
                      {item.label}
                    </p>
                    <p className="mt-2 text-xl font-bold text-gray-900">
                      {item.value}
                    </p>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-sm leading-6 text-gray-600">
                This report is prepared for internal IT review. Attention count
                highlights records containing pending, damaged, expired,
                maintenance or review-related statuses.
              </p>
            </div>

            <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
              <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                Applied Filters
              </p>
              <div className="mt-4 space-y-3">
                {appliedFilters.map((filter) => (
                  <div
                    key={filter.label}
                    className="flex justify-between gap-3 rounded-xl bg-gray-50 px-3 py-2 text-sm"
                  >
                    <span className="font-semibold text-gray-500">
                      {filter.label}
                    </span>
                    <span className="text-right font-bold text-gray-900">
                      {filter.value}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {attentionRecords > 0 && (
            <section className="report-section rounded-2xl border border-yellow-200 bg-yellow-50 p-4">
              <p className="text-sm font-bold text-yellow-900">
                Attention Highlights
              </p>
              <p className="mt-1 text-sm leading-6 text-yellow-800">
                {attentionRecords} records need review before this report is
                considered final for audit or management circulation.
              </p>
            </section>
          )}

          {data.length === 0 && (
            <section className="report-section rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-center shadow-sm">
              <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                Empty Report
              </p>
              <h2 className="mt-2 text-lg font-bold text-gray-900">
                No records available for this report
              </h2>
              <p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-gray-600">
                The report document structure is ready. Once filters or backend
                data return records, the table and summary will populate here.
              </p>
            </section>
          )}

          {data.length > 0 && (
            <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:hidden">
              <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                Mobile Record Summary
              </p>
              <div className="mt-4 space-y-3">
                {mobileRecords.map((record, index) => (
                  <div
                    key={`${title}-mobile-record-${index}`}
                    className="rounded-xl border border-gray-100 bg-gray-50 p-4"
                  >
                    {record.map(([key, value]) => (
                      <div
                        key={`${key}-${value}`}
                        className="flex justify-between gap-3 py-1 text-sm"
                      >
                        <span className="font-semibold capitalize text-gray-500">
                          {key.replace(/([A-Z])/g, " $1")}
                        </span>
                        <span className="text-right font-bold text-gray-900">
                          {String(value)}
                        </span>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </section>
          )}

          <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  Chart Preview
                </p>
                <h2 className="mt-1 text-lg font-bold text-gray-900">
                  Report distribution snapshot
                </h2>
              </div>
              <span className="w-fit rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-semibold text-gray-600">
                Frontend chart preview
              </span>
            </div>
            <div className="mt-5 space-y-4">
              {chartPreview.map((item) => (
                <div key={item.label}>
                  <div className="mb-2 flex items-center justify-between text-sm">
                    <span className="font-semibold text-gray-700">
                      {item.label}
                    </span>
                    <span className="font-bold text-gray-900">
                      {item.value}
                    </span>
                  </div>
                  <div className="h-3 rounded-full bg-gray-100">
                    <div
                      className="h-3 rounded-full bg-gray-900"
                      style={{
                        width: `${Math.max(
                          (item.value / maxChartValue) * 100,
                          item.value > 0 ? 12 : 0
                        )}%`,
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </section>

          {children}

          <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Audit Trail Preview
            </p>
            <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-4">
              {auditTrail.map((item) => (
                <div
                  key={item.label}
                  className="rounded-xl border border-gray-100 bg-gray-50 p-3"
                >
                  <p className="text-xs font-semibold text-gray-500">
                    {item.label}
                  </p>
                  <p className="mt-2 text-sm font-bold text-gray-900">
                    {item.value}
                  </p>
                </div>
              ))}
            </div>
          </section>

          <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Reviewer Notes & Action Items
            </p>
            <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">
              {[
                "Review records marked for attention",
                "Confirm department-wise ownership",
                "Update backend data before final export",
              ].map((note) => (
                <div
                  key={note}
                  className="rounded-xl border border-gray-100 bg-gray-50 p-4 text-sm font-semibold text-gray-700"
                >
                  {note}
                </div>
              ))}
            </div>
          </section>

          <section className="report-section rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Approval & Sign-off
            </p>
            <div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">
              {["Prepared By", "Reviewed By", "Approved By"].map((label) => (
                <div
                  key={label}
                  className="rounded-xl border border-gray-200 bg-gray-50 p-4"
                >
                  <p className="text-sm font-bold text-gray-900">{label}</p>
                  <div className="mt-10 border-t border-gray-300 pt-2 text-xs font-semibold text-gray-500">
                    Name, signature and date
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        <div className="report-footer relative z-10 border-t border-gray-200 bg-gray-50 px-5 py-4 text-xs text-gray-600">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <p className="font-semibold">
              Confidential - For internal IT department use only
            </p>
            <p>
              {title} | {reportId} | Page <span className="page-number" />
            </p>
          </div>
        </div>
      </section>
    </LayoutWrapper>
  );
}
